CookingSchool.Portal/Models/RecipeViewModel.cs
using CookingSchool.DAL.Models;
using System;
using System.Collections.Generic;

namespace CookingSchool.Models
{
    public class RecipeViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public int? ImageId { get; set; }

        public Image Image { get; set; }

        public ICollection<Ingredient> Ingredients { get; set; }

        public DateTime CreatedOnUtc { get; set; }

        public DateTime ModifiedOnUtc { get; set; }

        public int AuthorId { get; set; }

        public Author Author { get; set; }

        public int MealTypeId { get; set; }

        public MealType MealType { get; set; }
    }
}

CookingSchool.Portal/Controllers/RecipesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CookingSchool.Models;
using CookingSchool.DAL.Models;
using CookingSchool.Portal.Models;
using CookingSchool.DAL.Repositories;
using System.Collections.Generic;
using CookingSchool.Portal.Utils;
using AutoMapper;
using System;

namespace CookingSchool.Portal.Controllers
{
    [RoutePrefix("recipes")]
    public class RecipesController : Controller
    {
        private IMapper _mapper;
        private IRepository<Recipe> _repository;
        private IRepository<MealType> _mealRepository;
        private IRepository<Author> _authorRepository;
        private IImageManager _imageManager;

        public RecipesController(IRepository<Recipe> repository, IRepository<MealType> mealRepository,
            IRepository<Author> authorRepository, IImageManager imageManager, IMapper mapper)
        {
            _imageManager = imageManager;
            _repository = repository;
            _mealRepository = mealRepository;
            _authorRepository = authorRepository;
            _mapper = mapper;
        }

        public ActionResult RecipesList(int? page)
        {
            var recipes = _repository.GetAll();
            var recipesViewModel = _mapper.Map<IEnumerable<Recipe>, IEnumerable<RecipeViewModel>>(recipes);

            var pager = new Pager(recipesViewModel.Count(), page);

            var viewModel = new PaginationViewModel
            {
                Items = recipesViewModel.Skip((pager.CurrentPage - 1) * pager.PageSize).Take(pager.PageSize).ToList(),
                Pager = pager
            };

            return View("RecipesList", viewModel);
        }

        // GET: Recipes
        public ActionResult Index(int? page)
        {
            var recipes = _repository.GetAll();

            var recipesViewModel = new List<RecipeViewModel>();

            foreach (var item in recipes)
            {
                var recipeViewModel = _mapper.Map<Recipe, RecipeViewModel>(item);

                recipesViewModel.Add(recipeViewModel);

            }
            var pager = new Pager(recipesViewModel.Count(), page);

            var viewModel = new PaginationViewModel
            {
                Items = recipesViewModel.Skip((pager.CurrentPage - 1) * pager.PageSize).Take(pager.PageSize).ToList(),
                Pager = pager
            };

            return View("Index", viewModel);
        }

        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            var recipe = _repository.GetById(id);

            if (recipe == null)
            {
                return HttpNotFound();
            }
            var modelViewRecipe = _mapper.Map<Recipe, RecipeViewModel>(recipe);

            return View("Details", modelViewRecipe);
        }

        //[Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            AuthorListFill();
            MealTypeFill();

            var modelViewRecipe = new RecipeViewModel();

            return View(modelViewRecipe);
        }

        [HttpPost]
        public ActionResult Create(RecipeViewModel model)
        {
            return View("CreateImage");
        }

        [HttpPost]
        public ActionResult CreateImage(RecipeViewModel model)
        {
            var recipe = _mapper.Map<RecipeViewModel, Recipe>(model);

            _repository.Add(recipe);

            return RedirectToAction("Index");
        }

        // GET: Recipes/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var recipe = _repository.GetById(id);

          

            if (recipe == null)
            {
                return HttpNotFound();
            }

            AuthorListFill();
            MealTypeFill();

            var modelViewRecipe = _mapper.Map<Recipe, RecipeViewModel>(recipe);

            return View(modelViewRecipe);
        }

        [HttpPost]
        [Route("{Id}")]
        public ActionResult Edit(RecipeViewModel model)
        {

            var recipe = _mapper.Map<RecipeViewModel, Recipe>(model);

            recipe.ModifiedOnUtc = DateTime.UtcNow;
            recipe.CreatedOnUtc = DateTime.UtcNow;

            _repository.Update(recipe);

            return View("Details", model);
        }

        // GET: Recipes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var recipe = _repository.GetById(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var recipe = _repository.GetById(id);
            _repository.Delete(recipe);
            return RedirectToAction("Index");
        }

        public void AuthorListFill()
        {
            var authors = _authorRepository.GetAll();

            var authorList = new List<SelectListItem>();

            foreach (var item in authors)
            {
                var text = item.Surname + " " + item.Name;
                var value = item.Id;
                authorList.Add(new SelectListItem { Text = text, Value = value.ToString() });
            }

            ViewData["Author"] = authorList;
        }

        public void MealTypeFill()
        {
            var mealTypes = _mealRepository.GetAll();

            ViewData["MealType"] = new SelectList(mealTypes, "Id", "Name");
        }
    }
}

CookingSchool.Portal/Views/Recipes/Create.cshtml
@model CookingSchool.Models.RecipeViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "recipes"))
{
    //@Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2"  })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @Id = "txtTitle" } })
                @Html.ValidationMessageFor(model => model.Title, "Can not be empty", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 50, new { @class = "form-control", @Id = "txtDescription"})
                @Html.ValidationMessageFor(model => model.Description, "Can not be empty", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MealType.Name, "MealType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MealType", null , htmlAttributes: new { @class = "form-control" , @Id = "ddlMealType"})
                @Html.ValidationMessageFor(model => model.MealType.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Author", null,  htmlAttributes : new { @class = "form-control", @id = "ddlAuthor" } )
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>
       
        
        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">

                <input type="submit" name="BtnNext" value="Next" class="btn btn-default" />

            </div>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">

    $('form').submit(function () {

        var titleValue = $('#txtTitle').val();
        var descriptionValue = $('#txtDescription').val();
        var mealTypeValue = $('#ddlMealType').val();
        var authorValue = $('#ddlAuthor').val();

        if (titleValue == "" || descriptionValue == "")
        {
            window.alert("You didn't input value");
            return false;
        }
       
        sessionStorage.setItem("title", titleValue);
        sessionStorage.setItem("description", descriptionValue);
        sessionStorage.setItem("mealType", mealTypeValue);
        sessionStorage.setItem("author", authorValue);
    });


    function GetParameterName(name, url)
    {
        if (!url) url = window.location.href;

        name = name.replace((/[\[\]]/g, "\\$&"));

        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)");

        results = regex.exec(url);

        if (!results) return null;

        if (!results[2]) return '';

        return decodeURIComponent(results[2].replace(/\+/g, " "));
    }

</script>

CookingSchool.Portal/Views/Recipes/CreateImage.cshtml
@model CookingSchool.Models.RecipeViewModel

@{
    ViewBag.Title = "CreateImage";
}

<h2>CreateImage</h2>
@using (Html.BeginForm())
{
    <form id="myForm" enctype="multipart/form-data">
        <div class="form-group">
            <input type="file" id="uploadImg" name="imgFile" multiple />
            <input type="button" value="LOAD" id="btnUploadImg" />
        </div>

        <div class="form-group">
            <label id="ImgId"></label>
        </div>
        
        <div class="col-md-2 thumbnail" id="uploadedImage">

        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">

                <input type="submit" id="BtnPrevious"  name="BtnPrevious" value="Previous" class="btn btn-default" />

                <input type="submit" id="BtnFinish" name="BtnNext" value="Finish" class="btn btn-default" />

            </div>

        </div>
    </form>
}
<script type="text/javascript">

    $(document).ready(function () {
        var passTitle = sessionStorage.getItem("title");
        var passDescription = sessionStorage.getItem("description");
        var passMealType = parseInt(sessionStorage.getItem("mealType"));
        var passAuthor = sessionStorage.getItem("author");
        var data;
        $('#btnUploadImg').click(function () {

            var formData = new FormData();
            $.each($('#uploadImg')[0].files, function (i, file) {
                formData.append('file-' + i, file);
            });
            var baseUrl = '@Url.Content("~/")';
            $.ajax({
                type: 'POST',
                url:"https://jw-cookingschool-portal.azurewebsites.net/images",
                contentType: false,
                processData: false,
                data: formData,
                success: function (response) {
                    $('#ImgId').html(response.Id);
                    $('#uploadedImage').append('<img src="https://jw-cookingschool-portal.azurewebsites.net/images/' + response.Id + '/thumbnail?width=120&height=120"/>');
                    sessionStorage.clear();
                    data = { Title: passTitle, Description: passDescription, AuthorId: parseInt(passAuthor), MealTypeId: passMealType, ImageId: response.Id };
                }

            });

            return false;
        });

        $('#BtnPrevious').click(function () {
            document.location = '@Url.Action("Create", "recipes", Model)';
            return false;
        });

        $('#BtnFinish').click(function () {
            debugger;

            $.ajax({
                method: 'POST',
                url: '@Url.Action("CreateImage", "recipes")',
                data: data,
                success: function (res) {
                    console.log("Recipe has been added");
                },
                error: function (jqXHR, textStatuse, errorThrown) {
                    console.log("jqXHR.status");
                    console.log(jqXHR.status);
                    console.log("errorThrown");
                    console.log(jqXHR.status);
                    debugger;
                }
            });
            window.location.href = '@Url.Action("RecipesList","recipes")';
            return false;
        });
    });

</script>

CookingSchool.Portal/Views/Recipes/Delete.cshtml
@model CookingSchool.DAL.Models.Recipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MealType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MealType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOnUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOnUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CookingSchool.Portal/Views/Recipes/Details.cshtml
@model CookingSchool.Models.RecipeViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Surname)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Image.Name)*@
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Image.Name)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MealType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MealType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOnUtc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CookingSchool.Portal/Views/Recipes/Edit.cshtml
@model CookingSchool.Models.RecipeViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


    @*@Html.AntiForgeryToken()*@
    
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @Id = "modelId" } })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @Id = "modelTitle" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model =>model.Description, 10, 50, new  { @class = "form-control", @Id = "modelDescription" } )
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MealType, "MealType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MealType", null, htmlAttributes: new { @class = "form-control", @Id = "ddlMealType" })
                @Html.ValidationMessageFor(model => model.MealType.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Author", null, htmlAttributes: new { @class = "form-control", @Id = "ddlAuthor" })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageId, "Image", htmlAttributes: new {@class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageId, new { type = "file",  @class = "col-md-4", @Id = "imageUploader" })
                <input type="button" id="editImageUpload" class="btn-default" value="UPLOAD"/>
            </div>
            <div class="col-md-4">
                <img id="recieImgContainer" src="" alt="Recipe does not contain image" class="col-md-4" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnSubmit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var data;
        var imageId;
        var formData = new FormData();

        $('#recieImgContainer').attr("src", "https://jw-cookingschool-portal.azurewebsites.net/images/@Model.ImageId/thumbnail?width=120&height=120");

        $('#editImageUpload').click(function () {

            $.each($('#imageUploader')[0].files, function (i, file) {
                formData.append('file-' + i, file);
            });

            $.ajax({
                method: 'POST',
                type: 'POST',
                url:"https://jw-cookingschool-portal.azurewebsites.net/images",
                contentType: false,
                processData: false,
                data: formData,
                success: function (response) {
                    $('#recieImgContainer').attr("src", "https://jw-cookingschool-portal.azurewebsites.net/images/" + response.Id + "/thumbnail?width=140&height=120");

                    data = { Id: @Model.Id, Title: $('#modelTitle').val(), Description: $('#modelDescription').text(), MealTypeId: $('#ddlMealType').val(), AuthorId: $('#ddlAuthor').val(), ImageId: response.Id };
                    imageId = response.Id;
                },
                error: function (jqXHR, errorThrown) {
                    console.log("jqXHR.status:");
                    console.log(jqXHR.status);
                    console.log("errorThrown:");
                    console.log(jqXHR.status);
                }
            })
            return false;
        });

        $('#btnSubmit').click(function () {
            var modelImg = @Model.ImageId;
            if (imageId != null)
            {
            data = { Id: @Model.Id, Title: $('#modelTitle').val(), Description: $('#modelDescription').text(), MealTypeId: $('#ddlMealType').val(), AuthorId: $('#ddlAuthor').val(), ImageId: imageId };
            }
            else
            {
            data = { Id: @Model.Id, Title: $('#modelTitle').val(), Description: $('#modelDescription').text(), MealTypeId: $('#ddlMealType').val(), AuthorId: $('#ddlAuthor').val(), ImageId: modelImg};
            }
               $.ajax({
                method: 'POST',
                url: '@Url.Action("Edit", "Recipes")',
                data: data,
                success: function () {
                    window.location.href = '@Url.Action("RecipesList","recipes")';
                },
                error: function (jqXHR, errorThrown) {
                    console.log("jqXHR.status:");
                    console.log(jqXHR.status);
                    console.log("errorThrown:");
                    console.log(jqXHR.status);
                }
            })

        });
    })

</script>

CookingSchool.Portal/Views/Recipes/Index.cshtml
@model CookingSchool.Portal.Models.PaginationViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            AUTHOR
        </th>
        <th>
            IMAGE
        </th>
        <th>
            MEAL TYPE 
        </th>
        <th>
           TITLE
        </th>
        <th>
            DESCRIPTION
        </th>
        <th>
            CreatedOnUtc
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Items) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem =>  item.Author.Name) 
            @Html.DisplayFor(modelItem => item.Author.Surname)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Image.Name)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MealType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOnUtc)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}


</table>
@if (Model.Pager.EndPage > 1)
            {
    <ul class="pagination">
        @if (Model.Pager.CurrentPage > 1)
        {
            <li>
                <a href="~/Recipes/Index">First</a>
            </li>
                        <li>
                            <a href="~/Recipes/Index?page=@(Model.Pager.CurrentPage -1)">Previous</a>
                        </li>
        }
        @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
            <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                <a href="~/Recipes/Index?page=@page">@page</a>
            </li>
        }
        @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
            <li>
                <a href="~/Recipes/Index?page=@(Model.Pager.CurrentPage + 1)">Next</a>
            </li>
                        <li>
                            <a href="~/Recipes/Index?page=@(Model.Pager.TotalPages)">Last</a>
                        </li>
        }
    </ul>

}

CookingSchool.Portal/Views/Recipes/RecipesList.cshtml
@model CookingSchool.Portal.Models.PaginationViewModel
@{
    ViewBag.Title = "Przepisy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div  class="panel-default">
    <div class="panel-heading">OSTATNIO DODANE PRZEPISY</div>
    <div class="panel-body">
        <div  class="list-group">
            <ul style="list-style:none">
                @foreach (var item in Model.Items)
                {
                    <li>@Html.Partial("_Recipe", item)</li>
                }
            </ul>

            @if (Model.Pager.EndPage > 1)
            {
                <ul class="pagination">
                    @if (Model.Pager.CurrentPage > 1)
                    {
                        <li>
                            <a href="~/Recipes/RecipesList">First</a>
                        </li>
                        <li>
                            <a href="~/Recipes/RecipesList?page=@(Model.Pager.CurrentPage -1)">Previous</a>
                        </li>
                    }
                    @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                        <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                            <a href="~/Recipes/RecipesList?page=@page">@page</a>
                        </li>
                    }
                    @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                        <li>
                            <a href="~/Recipes/RecipesList?page=@(Model.Pager.CurrentPage + 1)">Next</a>
                        </li>
                        <li>
                            <a href="~/Recipes/RecipesList?page=@(Model.Pager.TotalPages)">Last</a>
                        </li>
                    }
                </ul>

            }
         


        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        $(document).ready(function () {
            $(".recipe-date").each(function () {
                
                        var format = 'DD.MM.YYYY HH:mm:ss';
                        var utcTime = moment.utc($(this).text()).toDate();
                        var local = moment(utcTime).local().format(format);
                        $(this).text(local);
                       

            })
        });

    </script>
}

CookingSchool.Portal/Views/Recipes/Success.cshtml
@model CookingSchool.Models.RecipeViewModel

@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>

CookingSchool.Portal/Views/Recipes/_Recipe.cshtml
@model CookingSchool.Models.RecipeViewModel


<div>
    <a href="@Url.Action("Details","recipes")/@Model.Id" class="list-group-item col-md-12" style=" display:inline-block;" >
        
        <div class="col-md-4">
            <img id="recieImgContainer" src="https://jw-cookingschool-portal.azurewebsites.net/images/@Model.ImageId/thumbnail?width=200&height=180" alt="Recipe does not contain image" class="col-md-4" />
        </div>
        <div id="recipeViewModel" class="col-md-8" >
           
            <h4>@Model.Title</h4>

            <p>@Model.Description</p>

            <h6>@Model.Author.Name @Model.Author.Surname <span>@Model.CreatedOnUtc</span></h6>  @*selector*@

        </div>
    </a>
 </div>